// Generated by python -m scripts.generate_api_types. Do not edit.

export interface ApiError {
  code: string;
  message: string;
  details: Array<ErrorDetail>;
}

export interface CreateJobRequest {
  url: string;
  selection?: PlaylistSelection;
  settings?: DownloadSettings;
}

export interface DownloadSettings {
  mode: "video" | "audio";
  quality: "best" | "1080p" | "720p" | "480p";
  format: "auto" | "mp4" | "webm" | "mp3" | "m4a" | "flac" | "wav";
  destination: string;
  filename: string | null;
}

export interface ErrorDetail {
  location: Array<string | number>;
  message: string;
  code: string;
}

export interface ErrorResponse {
  error: ApiError;
}

export interface HealthResponse {
  status: "ok";
}

export interface JobActionRequest {
  action: "pause" | "resume" | "cancel" | "retry";
}

export interface JobProgress {
  downloaded_bytes: number;
  total_bytes: number | null;
  percent: number | null;
  speed_bytes_per_second: number | null;
  eta_seconds: number | null;
}

export interface JobResponse {
  id: string;
  source_url: string;
  title: string | null;
  status: "queued" | "downloading" | "paused" | "complete" | "canceled" | "failed";
  selection: PlaylistSelection;
  settings: DownloadSettings;
  progress: JobProgress;
  output_name: string | null;
  error: ApiError | null;
  created_at: string;
  updated_at: string;
}

export interface JobsResponse {
  jobs: Array<JobResponse>;
}

export interface MediaFormat {
  id: string;
  extension: string;
  video_codec: string | null;
  audio_codec: string | null;
  width: number | null;
  height: number | null;
  filesize_bytes: number | null;
}

export interface PlaylistSelection {
  item_indices: Array<number>;
}

export interface PreviewItem {
  id: string;
  url: string;
  title: string;
  uploader: string | null;
  thumbnail_url: string | null;
  duration_seconds: number | null;
  playlist_index: number | null;
  formats: Array<MediaFormat>;
}

export interface PreviewRequest {
  url: string;
}

export interface PreviewResponse {
  source_url: string;
  kind: "video" | "playlist";
  title: string;
  items: Array<PreviewItem>;
  total_items: number | null;
}

export interface SettingsResponse {
  defaults: DownloadSettings;
  allowed_modes: Array<"video" | "audio">;
  allowed_qualities: Array<string>;
  allowed_formats: Array<string>;
  destinations: Array<string>;
  worker_count: number;
}

export interface UrlRequest {
  url: string;
}

export type DownloadSettingsInput = Partial<DownloadSettings>;
export type PlaylistSelectionInput = Partial<PlaylistSelection>;
export type CreateJobInput = Omit<CreateJobRequest, "settings" | "selection"> & {
  settings?: DownloadSettingsInput;
  selection?: PlaylistSelectionInput;
};
