// Generated by python -m scripts.generate_api_types. Do not edit.

export interface ApiError {
  code: string;
  message: string;
  details: Array<ErrorDetail>;
}

export interface CreateJobRequest {
  url: string;
  selection?: PlaylistSelection;
  settings?: DownloadSettings;
}

export interface DownloadSettings {
  mode: "video" | "audio";
  quality: "best" | "1080p" | "720p" | "480p";
  format: "auto" | "mp4" | "webm" | "mp3" | "m4a" | "flac" | "wav";
  destination: string;
  filename: string | null;
  subtitles: boolean;
  automatic_captions: boolean;
  subtitle_languages: Array<string>;
  subtitle_format: "best" | "srt" | "vtt" | "ass";
  embed_subtitles: boolean;
  embed_metadata: boolean;
  save_thumbnail: boolean;
  embed_thumbnail: boolean;
  embed_chapters: boolean;
  split_chapters: boolean;
  remux: "auto" | "mp4" | "mkv" | "webm";
  use_archive: boolean;
  playlist_start: number;
  playlist_end: number | null;
  minimum_duration: number | null;
  maximum_duration: number | null;
  output_template: string | null;
  file_conflict: "rename" | "skip" | "fail";
  retry_count: number;
  rate_limit: number | null;
  fragment_concurrency: number;
  proxy: string | null;
  http_headers: Array<string>;
  use_cookie_file: boolean;
  custom_options: Array<"--prefer-free-formats" | "--no-playlist" | "--playlist-reverse" | "--check-formats">;
}

export interface DownloadedItem {
  filename: string;
  title: string;
  thumbnail_url: string | null;
}

export interface ErrorDetail {
  location: Array<string | number>;
  message: string;
  code: string;
}

export interface ErrorResponse {
  error: ApiError;
}

export interface HealthResponse {
  status: "ok";
}

export interface JobActionRequest {
  action: "pause" | "resume" | "cancel" | "retry";
}

export interface JobProgress {
  downloaded_bytes: number;
  total_bytes: number | null;
  percent: number | null;
  speed_bytes_per_second: number | null;
  eta_seconds: number | null;
}

export interface JobResponse {
  id: string;
  source_url: string;
  title: string | null;
  status: "queued" | "downloading" | "paused" | "complete" | "canceled" | "failed";
  selection: PlaylistSelection;
  settings: DownloadSettings;
  progress: JobProgress;
  thumbnail_url: string | null;
  playlist_title: string | null;
  output_folder: string | null;
  downloaded_items: Array<DownloadedItem>;
  output_name: string | null;
  output_files: Array<string>;
  output_directory: "job" | "root";
  error: ApiError | null;
  created_at: string;
  updated_at: string;
}

export interface JobsResponse {
  jobs: Array<JobResponse>;
}

export interface MediaFormat {
  id: string;
  extension: string;
  video_codec: string | null;
  audio_codec: string | null;
  width: number | null;
  height: number | null;
  filesize_bytes: number | null;
}

export interface PlaylistSelection {
  item_indices: Array<number>;
}

export interface PreviewItem {
  id: string;
  url: string;
  title: string;
  uploader: string | null;
  thumbnail_url: string | null;
  duration_seconds: number | null;
  playlist_index: number | null;
  formats: Array<MediaFormat>;
  formats_checked: boolean;
}

export interface PreviewRequest {
  url: string;
}

export interface PreviewResponse {
  source_url: string;
  kind: "video" | "playlist";
  title: string;
  items: Array<PreviewItem>;
  total_items: number | null;
}

export interface SettingsResponse {
  defaults: DownloadSettings;
  allowed_modes: Array<"video" | "audio">;
  allowed_qualities: Array<string>;
  allowed_formats: Array<string>;
  destinations: Array<string>;
  worker_count: number;
  cookie_file_available: boolean;
}

export interface UrlRequest {
  url: string;
}

export type DownloadSettingsInput = Partial<DownloadSettings>;
export type PlaylistSelectionInput = Partial<PlaylistSelection>;
export type CreateJobInput = Omit<CreateJobRequest, "settings" | "selection"> & {
  settings?: DownloadSettingsInput;
  selection?: PlaylistSelectionInput;
};
