"""Generate response and request TypeScript types from Pydantic JSON Schema.

Run from the repository root: python -m scripts.generate_api_types
Use --check in validation to detect stale generated contracts.
Request types allow omitted fields with defaults; response types describe the
complete model_dump() payload (exclude_unset/exclude_none must not be used).
"""

import argparse
import json
from pathlib import Path

from api import contracts


def ts_type(schema: dict) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in schema:
        return " | ".join(ts_type(part) for part in schema["anyOf"])
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{ts_type(schema['items'])}>"
    if kind in ("string", "boolean", "null"):
        return kind
    if kind in ("integer", "number"):
        return "number"
    raise ValueError(f"Unsupported schema: {schema}")


def generate() -> str:
    models = {
        name: value
        for name, value in vars(contracts).items()
        if isinstance(value, type)
        and issubclass(value, contracts.Contract)
        and value is not contracts.Contract
    }
    definitions = {}
    for name, model in models.items():
        schema = model.model_json_schema()
        definitions.update(schema.pop("$defs", {}))
        definitions[name] = schema
    lines = ["// Generated by python -m scripts.generate_api_types. Do not edit.", ""]
    for name, schema in sorted(definitions.items()):
        lines.append(f"export interface {name} {{")
        required = set(schema.get("required", []))
        for field, value in schema["properties"].items():
            optional = "?" if name.endswith("Request") and field not in required else ""
            lines.append(f"  {field}{optional}: {ts_type(value)};")
        lines.extend(["}", ""])
    # Nested request settings also accept omissions for server defaults.
    lines.extend([
        'export type DownloadSettingsInput = Partial<DownloadSettings>;',
        'export type PlaylistSelectionInput = Partial<PlaylistSelection>;',
        'export type CreateJobInput = Omit<CreateJobRequest, "settings" | "selection"> & {',
        '  settings?: DownloadSettingsInput;',
        '  selection?: PlaylistSelectionInput;',
        '};',
        '',
    ])
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = Path(__file__).resolve().parents[1] / "web/src/api/contracts.ts"
    content = generate()
    if args.check:
        if not target.exists() or target.read_text() != content:
            raise SystemExit("API types are stale; run python -m scripts.generate_api_types")
    else:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)
